# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Dashboards.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QStandardItem, QStandardItemModel 
from PyQt5.QtCore import QSortFilterProxyModel
import database

class Ui_DashboardsWindow(object):
    def setupUi(self, DashboardsWindow):
        DashboardsWindow.setObjectName("DashboardsWindow")
        DashboardsWindow.resize(800, 600)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/fugue-icons-3.5.6/icons/user-business.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        DashboardsWindow.setWindowIcon(icon)
        DashboardsWindow.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"font-weight:bold;\n"
"color:rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(DashboardsWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.homeButton = QtWidgets.QPushButton(self.widget)
        self.homeButton.setMinimumSize(QtCore.QSize(80, 0))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.homeButton.setFont(font)
        self.homeButton.setStyleSheet("QPushButton{\n"
"background-image: url(:/newPrefix/fugue-icons-3.5.6/icons/home-medium.png);\n"
"background-repeat: no-repeat;\n"
"border: 2px;\n"
"border-style:solid;\n"
"border-radius:6px;\n"
"background-color:rgb(0, 0, 0);\n"
"padding: 4px;\n"
"color:rgb(255, 255, 255);\n"
"border-color:rgb(81, 0, 255);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"border-bottom-color:rgb(0, 196, 113);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color:rgb(79, 79, 79)\n"
"}")
        self.homeButton.setObjectName("homeButton")
        self.horizontalLayout.addWidget(self.homeButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.userManagementButton = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.userManagementButton.setFont(font)
        self.userManagementButton.setStyleSheet("QPushButton{\n"
"border: 2px;\n"
"border-style:solid;\n"
"border-radius:6px;\n"
"background-color:rgb(0, 0, 0);\n"
"padding: 4px;\n"
"color:rgb(255, 255, 255);\n"
"border-color:rgb(81, 0, 255);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"border-bottom-color:rgb(0, 196, 113);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color:rgb(79, 79, 79)\n"
"}")
        self.userManagementButton.setObjectName("userManagementButton")
        self.horizontalLayout.addWidget(self.userManagementButton)
        self.employeeInformationButton = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.employeeInformationButton.setFont(font)
        self.employeeInformationButton.setStyleSheet("QPushButton{\n"
"border: 2px;\n"
"border-style:solid;\n"
"border-radius:6px;\n"
"background-color:rgb(0, 0, 0);\n"
"padding: 4px;\n"
"color:rgb(255, 255, 255);\n"
"border-color:rgb(81, 0, 255);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"border-bottom-color:rgb(0, 196, 113);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color:rgb(79, 79, 79)\n"
"}")
        self.employeeInformationButton.setObjectName("employeeInformationButton")
        self.horizontalLayout.addWidget(self.employeeInformationButton)
        self.leaveManagementButton = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.leaveManagementButton.setFont(font)
        self.leaveManagementButton.setStyleSheet("QPushButton{\n"
"border: 2px;\n"
"border-style:solid;\n"
"border-radius:6px;\n"
"background-color:rgb(0, 0, 0);\n"
"padding: 4px;\n"
"color:rgb(255, 255, 255);\n"
"border-color:rgb(81, 0, 255);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"border-bottom-color:rgb(0, 196, 113);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color:rgb(79, 79, 79)\n"
"}")
        self.leaveManagementButton.setObjectName("leaveManagementButton")
        self.horizontalLayout.addWidget(self.leaveManagementButton)
        self.logoutButton = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.logoutButton.setFont(font)
        self.logoutButton.setStyleSheet("QPushButton{\n"
"border: 2px;\n"
"border-style:solid;\n"
"border-radius:6px;\n"
"background-color:rgb(0, 0, 0);\n"
"padding: 4px;\n"
"color:rgb(255, 255, 255);\n"
"border-color:rgb(81, 0, 255);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"border-bottom-color:rgb(0, 196, 113);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color:rgb(79, 79, 79)\n"
"}")
        self.logoutButton.setObjectName("logoutButton")
        self.horizontalLayout.addWidget(self.logoutButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.stackedWidget = QtWidgets.QStackedWidget(self.widget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.homePage = QtWidgets.QWidget()
        self.homePage.setObjectName("homePage")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.homePage)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_3 = QtWidgets.QLabel(self.homePage)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color:rgb(255, 255, 255)")
        self.label_3.setObjectName("label_3")
        self.verticalLayout_5.addWidget(self.label_3, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem1)
        self.page1UserManagementButton = QtWidgets.QPushButton(self.homePage)
        self.page1UserManagementButton.setMinimumSize(QtCore.QSize(140, 40))
        self.page1UserManagementButton.setMaximumSize(QtCore.QSize(140, 40))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.page1UserManagementButton.setFont(font)
        self.page1UserManagementButton.setStyleSheet("QPushButton{\n"
"border: 2px;\n"
"border-style:solid;\n"
"border-radius:6px;\n"
"background-color:rgb(0, 0, 0);\n"
"padding: 4px;\n"
"color:rgb(255, 255, 255);\n"
"border-color:rgb(81, 0, 255);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"border-bottom-color:rgb(0, 196, 113);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color:rgb(79, 79, 79)\n"
"}")
        self.page1UserManagementButton.setObjectName("page1UserManagementButton")
        self.verticalLayout_6.addWidget(self.page1UserManagementButton, 0, QtCore.Qt.AlignLeft)
        self.page1EmployeeInformationButton = QtWidgets.QPushButton(self.homePage)
        self.page1EmployeeInformationButton.setMinimumSize(QtCore.QSize(140, 40))
        self.page1EmployeeInformationButton.setMaximumSize(QtCore.QSize(140, 40))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.page1EmployeeInformationButton.setFont(font)
        self.page1EmployeeInformationButton.setStyleSheet("QPushButton{\n"
"border: 2px;\n"
"border-style:solid;\n"
"border-radius:6px;\n"
"background-color:rgb(0, 0, 0);\n"
"padding: 4px;\n"
"color:rgb(255, 255, 255);\n"
"border-color:rgb(81, 0, 255);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"border-bottom-color:rgb(0, 196, 113);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color:rgb(79, 79, 79)\n"
"}")
        self.page1EmployeeInformationButton.setObjectName("page1EmployeeInformationButton")
        self.verticalLayout_6.addWidget(self.page1EmployeeInformationButton, 0, QtCore.Qt.AlignLeft)
        self.page1LeaveManagementButton = QtWidgets.QPushButton(self.homePage)
        self.page1LeaveManagementButton.setMinimumSize(QtCore.QSize(140, 40))
        self.page1LeaveManagementButton.setMaximumSize(QtCore.QSize(140, 40))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.page1LeaveManagementButton.setFont(font)
        self.page1LeaveManagementButton.setStyleSheet("QPushButton{\n"
"border: 2px;\n"
"border-style:solid;\n"
"border-radius:6px;\n"
"background-color:rgb(0, 0, 0);\n"
"padding: 4px;\n"
"color:rgb(255, 255, 255);\n"
"border-color:rgb(81, 0, 255);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"border-bottom-color:rgb(0, 196, 113);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color:rgb(79, 79, 79)\n"
"}")
        self.page1LeaveManagementButton.setObjectName("page1LeaveManagementButton")
        self.verticalLayout_6.addWidget(self.page1LeaveManagementButton, 0, QtCore.Qt.AlignLeft)
        self.page1EmployeeRecruitmentButton = QtWidgets.QPushButton(self.homePage)
        self.page1EmployeeRecruitmentButton.setMinimumSize(QtCore.QSize(140, 40))
        self.page1EmployeeRecruitmentButton.setMaximumSize(QtCore.QSize(140, 40))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.page1EmployeeRecruitmentButton.setFont(font)
        self.page1EmployeeRecruitmentButton.setStyleSheet("QPushButton{\n"
"border: 2px;\n"
"border-style:solid;\n"
"border-radius:6px;\n"
"background-color:rgb(0, 0, 0);\n"
"padding: 4px;\n"
"color:rgb(255, 255, 255);\n"
"border-color:rgb(81, 0, 255);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"border-bottom-color:rgb(0, 196, 113);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color:rgb(79, 79, 79)\n"
"}")
        self.page1EmployeeRecruitmentButton.setObjectName("page1EmployeeRecruitmentButton")
        self.verticalLayout_6.addWidget(self.page1EmployeeRecruitmentButton, 0, QtCore.Qt.AlignLeft)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem2)
        self.horizontalLayout_2.addLayout(self.verticalLayout_6)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.homePage)
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap(":/newPrefix/images/analytics_bluepng-removebg-preview.png"))
        self.label_4.setObjectName("label_4")
        self.verticalLayout_4.addWidget(self.label_4, 0, QtCore.Qt.AlignHCenter)
        self.label_5 = QtWidgets.QLabel(self.homePage)
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap(":/newPrefix/images/product_analytics-removebg-preview.png"))
        self.label_5.setObjectName("label_5")
        self.verticalLayout_4.addWidget(self.label_5, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        self.label = QtWidgets.QLabel(self.homePage)
        self.label.setText("")
        self.label.setObjectName("label")
        self.verticalLayout_5.addWidget(self.label)
        self.stackedWidget.addWidget(self.homePage)
        self.employeeManagementPage = QtWidgets.QWidget()
        self.employeeManagementPage.setObjectName("employeeManagementPage")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.employeeManagementPage)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.employeeManagementPage)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_6 = QtWidgets.QLabel(self.employeeManagementPage)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_7.addWidget(self.label_6)
        self.empIdField = QtWidgets.QLineEdit(self.employeeManagementPage)
        self.empIdField.setMinimumSize(QtCore.QSize(200, 0))
        self.empIdField.setMaximumSize(QtCore.QSize(200, 16777215))
        self.empIdField.setStyleSheet("QLineEdit{\n"
"border: 4px;\n"
"color:rgb(255, 255, 255);\n"
"border-style : solid;\n"
"padding-left:6px;\n"
"border-color:rgb(0, 85, 255);\n"
"border-radius:8px;\n"
"}\n"
"QLineEdit:focus{\n"
"border-bottom-color:rgb(0, 196, 113)\n"
"}")
        self.empIdField.setObjectName("empIdField")
        self.verticalLayout_7.addWidget(self.empIdField)
        self.label_9 = QtWidgets.QLabel(self.employeeManagementPage)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_7.addWidget(self.label_9)
        self.empNameField = QtWidgets.QLineEdit(self.employeeManagementPage)
        self.empNameField.setMinimumSize(QtCore.QSize(200, 0))
        self.empNameField.setMaximumSize(QtCore.QSize(200, 16777215))
        self.empNameField.setStyleSheet("QLineEdit{\n"
"border: 4px;\n"
"color:rgb(255, 255, 255);\n"
"border-style : solid;\n"
"padding-left:6px;\n"
"border-color:rgb(0, 85, 255);\n"
"border-radius:8px;\n"
"}\n"
"QLineEdit:focus{\n"
"border-bottom-color:rgb(0, 196, 113)\n"
"}")
        self.empNameField.setObjectName("empNameField")
        self.verticalLayout_7.addWidget(self.empNameField)
        self.label_11 = QtWidgets.QLabel(self.employeeManagementPage)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_7.addWidget(self.label_11)
        self.genderComboBox = QtWidgets.QComboBox(self.employeeManagementPage)
        self.genderComboBox.setMinimumSize(QtCore.QSize(200, 0))
        self.genderComboBox.setMaximumSize(QtCore.QSize(200, 16777215))
        self.genderComboBox.setStyleSheet("QComboBox{\n"
"border: 4px;\n"
"color:rgb(255, 255, 255);\n"
"border-style : solid;\n"
"padding-left:6px;\n"
"border-color:rgb(0, 85, 255);\n"
"border-radius:8px;\n"
"}\n"
"QComboBox:focus{\n"
"border-bottom-color:rgb(0, 196, 113)\n"
"}")
        self.genderComboBox.addItem("Male")
        self.genderComboBox.addItem("Female")
        self.genderComboBox.setObjectName("genderComboBox")
        self.verticalLayout_7.addWidget(self.genderComboBox)
        self.label_10 = QtWidgets.QLabel(self.employeeManagementPage)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_7.addWidget(self.label_10)
        self.statusComboBox = QtWidgets.QComboBox(self.employeeManagementPage)
        self.statusComboBox.setMinimumSize(QtCore.QSize(200, 0))
        self.statusComboBox.setMaximumSize(QtCore.QSize(200, 16777215))
        self.statusComboBox.setStyleSheet("QComboBox{\n"
"border: 4px;\n"
"color:rgb(255, 255, 255);\n"
"border-style : solid;\n"
"padding-left:6px;\n"
"border-color:rgb(0, 85, 255);\n"
"border-radius:8px;\n"
"}\n"
"QComboBox:focus{\n"
"border-bottom-color:rgb(0, 196, 113)\n"
"}")
        self.statusComboBox.addItem("Active")
        self.statusComboBox.addItem("On Leave")
        self.statusComboBox.setObjectName("statusComboBox")
        self.verticalLayout_7.addWidget(self.statusComboBox)
        self.label_8 = QtWidgets.QLabel(self.employeeManagementPage)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_7.addWidget(self.label_8)
        self.positionComboBox = QtWidgets.QComboBox(self.employeeManagementPage)
        self.positionComboBox.setMinimumSize(QtCore.QSize(200, 0))
        self.positionComboBox.setMaximumSize(QtCore.QSize(200, 16777215))
        self.positionComboBox.setStyleSheet("QComboBox{\n"
"border: 4px;\n"
"color:rgb(255, 255, 255);\n"
"border-style : solid;\n"
"padding-left:6px;\n"
"border-color:rgb(0, 85, 255);\n"
"border-radius:8px;\n"
"}\n"
"QComboBox:focus{\n"
"border-bottom-color:rgb(0, 196, 113)\n"
"}")
        self.positionComboBox.addItem("Casual Employee")
        self.positionComboBox.addItem("Supervisor")
        self.positionComboBox.addItem("Department Head")
        self.positionComboBox.addItem("Manager")
        self.positionComboBox.setObjectName("positionComboBox")
        self.verticalLayout_7.addWidget(self.positionComboBox)
        self.label_7 = QtWidgets.QLabel(self.employeeManagementPage)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_7.addWidget(self.label_7)
        self.salaryFIeld = QtWidgets.QLineEdit(self.employeeManagementPage)
        self.salaryFIeld.setMinimumSize(QtCore.QSize(200, 0))
        self.salaryFIeld.setMaximumSize(QtCore.QSize(200, 16777215))
        self.salaryFIeld.setStyleSheet("QLineEdit{\n"
"border: 4px;\n"
"color:rgb(255, 255, 255);\n"
"border-style : solid;\n"
"padding-left:6px;\n"
"border-color:rgb(0, 85, 255);\n"
"border-radius:8px;\n"
"}\n"
"QLineEdit:focus{\n"
"border-bottom-color:rgb(0, 196, 113)\n"
"}")
        self.salaryFIeld.setObjectName("salaryFIeld")
        self.verticalLayout_7.addWidget(self.salaryFIeld)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem3)
        self.horizontalLayout_4.addLayout(self.verticalLayout_7)
        self.employeeManagementTreeView = QtWidgets.QTreeView(self.employeeManagementPage)
        self.employeeManagementTreeView.setMinimumSize(QtCore.QSize(520, 0))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.employeeManagementTreeView.setFont(font)
        self.employeeManagementTreeView.setStyleSheet("QTreeView{"
"border: 1px solid rgb(50, 50, 50);"  # Dark border color
"background-color: rgb(30, 30, 30);"  # Dark background color
"alternate-background-color: rgb(40, 40, 40);"  # Dark alternate background color
"color: rgb(200, 200, 200);"  # Light text color
"}"
"QHeaderView::section{"
"background-color: rgb(40, 40, 40);"  # Dark header background color
"color: rgb(200, 200, 200);"  # Light header text color
"}")
        self.employeeManagementTreeView.setObjectName("employeeManagementTreeView")
        self.horizontalLayout_4.addWidget(self.employeeManagementTreeView)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.addEmployeeButton = QtWidgets.QPushButton(self.employeeManagementPage)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.addEmployeeButton.setFont(font)
        self.addEmployeeButton.setStyleSheet("QPushButton{\n"
"border: 2px;\n"
"border-style:solid;\n"
"border-radius:6px;\n"
"background-color:rgb(0, 0, 0);\n"
"padding: 4px;\n"
"color:rgb(255, 255, 255);\n"
"border-color:rgb(81, 0, 255);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"border-bottom-color:rgb(0, 196, 113);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color:rgb(79, 79, 79)\n"
"}")
        self.addEmployeeButton.setObjectName("addEmployeeButton")
        self.horizontalLayout_3.addWidget(self.addEmployeeButton)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem5)
        self.updateEmployeeButton = QtWidgets.QPushButton(self.employeeManagementPage)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.updateEmployeeButton.setFont(font)
        self.updateEmployeeButton.setStyleSheet("QPushButton{\n"
"border: 2px;\n"
"border-style:solid;\n"
"border-radius:6px;\n"
"background-color:rgb(0, 0, 0);\n"
"padding: 4px;\n"
"color:rgb(255, 255, 255);\n"
"border-color:rgb(81, 0, 255);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"border-bottom-color:rgb(0, 196, 113);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color:rgb(79, 79, 79)\n"
"}")
        self.updateEmployeeButton.setObjectName("updateEmployeeButton")
        self.horizontalLayout_3.addWidget(self.updateEmployeeButton)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem6)
        self.deleteEployeeButton = QtWidgets.QPushButton(self.employeeManagementPage)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.deleteEployeeButton.setFont(font)
        self.deleteEployeeButton.setStyleSheet("QPushButton{\n"
"border: 2px;\n"
"border-style:solid;\n"
"border-radius:6px;\n"
"background-color:rgb(0, 0, 0);\n"
"padding: 4px;\n"
"color:rgb(255, 255, 255);\n"
"border-color:rgb(81, 0, 255);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"border-bottom-color:rgb(0, 196, 113);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color:rgb(79, 79, 79)\n"
"}")
        self.deleteEployeeButton.setObjectName("deleteEployeeButton")
        self.horizontalLayout_3.addWidget(self.deleteEployeeButton)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem7)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.stackedWidget.addWidget(self.employeeManagementPage)
        self.employeeInformationPage = QtWidgets.QWidget()
        self.employeeInformationPage.setObjectName("employeeInformationPage")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.employeeInformationPage)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_12 = QtWidgets.QLabel(self.employeeInformationPage)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_8.addWidget(self.label_12, 0, QtCore.Qt.AlignHCenter)
        self.searchField = QtWidgets.QLineEdit(self.employeeInformationPage)
        self.searchField.setMinimumSize(QtCore.QSize(200, 0))
        self.searchField.setMaximumSize(QtCore.QSize(200, 16777215))
        self.searchField.setStyleSheet("QLineEdit{\n"
"background-image: url(:/newPrefix/fugue-icons-3.5.6/icons/magnifier-left.png);\n"
"background-repeat: no-repeat;\n"
"background-position: right;\n"
"border: 2px;\n"
"color:rgb(255, 255, 255);\n"
"border-style : solid;\n"
"padding:4px;\n"
"border-color:rgb(0, 85, 255);\n"
"border-radius:8px;\n"
"}\n"
"QLineEdit:focus{\n"
"border-bottom-color:rgb(0, 196, 113)\n"
"}")
        self.searchField.setObjectName("searchField")
        self.verticalLayout_8.addWidget(self.searchField)
        self.employeeInfoTreeView = QtWidgets.QTreeView(self.employeeInformationPage)
        self.employeeInfoTreeView.setStyleSheet("QTreeView{"
"border: 1px solid rgb(50, 50, 50);"  # Dark border color
"background-color: rgb(30, 30, 30);"  # Dark background color
"alternate-background-color: rgb(40, 40, 40);"  # Dark alternate background color
"color: rgb(200, 200, 200);"  # Light text color
"}"
"QHeaderView::section{"
"background-color: rgb(40, 40, 40);"  # Dark header background color
"color: rgb(200, 200, 200);"  # Light header text color
"}")
        self.employeeInfoTreeView.setObjectName("employeeInfoTreeView")
        self.verticalLayout_8.addWidget(self.employeeInfoTreeView)
        self.stackedWidget.addWidget(self.employeeInformationPage)
        self.leaveManagamentPage = QtWidgets.QWidget()
        self.leaveManagamentPage.setObjectName("leaveManagamentPage")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.leaveManagamentPage)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_13 = QtWidgets.QLabel(self.leaveManagamentPage)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_10.addWidget(self.label_13, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_15 = QtWidgets.QLabel(self.leaveManagamentPage)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_9.addWidget(self.label_15)
        self.leavePageStatusComboBox = QtWidgets.QComboBox(self.leaveManagamentPage)
        self.leavePageStatusComboBox.setStyleSheet("QComboBox{\n"
"border: 4px;\n"
"color:rgb(255, 255, 255);\n"
"border-style : solid;\n"
"padding-left:6px;\n"
"border-color:rgb(0, 85, 255);\n"
"border-radius:8px;\n"
"}\n"
"QComboBox:focus{\n"
"border-bottom-color:rgb(0, 196, 113)\n"
"}")
        self.leavePageStatusComboBox.addItem("Active")
        self.leavePageStatusComboBox.addItem("On Leave")
        self.leavePageStatusComboBox.setObjectName("leavePageStatusComboBox")
        self.verticalLayout_9.addWidget(self.leavePageStatusComboBox)
        self.label_14 = QtWidgets.QLabel(self.leaveManagamentPage)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_9.addWidget(self.label_14)
        self.leaveDaysSpinBox = QtWidgets.QSpinBox(self.leaveManagamentPage)
        self.leaveDaysSpinBox.setStyleSheet("QSpinBox{\n"
"border: 4px;\n"
"color:rgb(255, 255, 255);\n"
"border-style : solid;\n"
"padding-left:6px;\n"
"border-color:rgb(0, 85, 255);\n"
"border-radius:8px;\n"
"}\n"
"QSpin\n"
"Box:focus{\n"
"border-bottom-color:rgb(0, 196, 113)\n"
"}")
        self.leaveDaysSpinBox.setMaximum(60)
        self.leaveDaysSpinBox.setObjectName("leaveDaysSpinBox")
        self.verticalLayout_9.addWidget(self.leaveDaysSpinBox)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem8)
        self.horizontalLayout_5.addLayout(self.verticalLayout_9)
        self.leaveTreeView = QtWidgets.QTreeView(self.leaveManagamentPage)
        self.leaveTreeView.setStyleSheet("QTreeView{"
"border: 1px solid rgb(50, 50, 50);"  # Dark border color
"background-color: rgb(30, 30, 30);"  # Dark background color
"alternate-background-color: rgb(40, 40, 40);"  # Dark alternate background color
"color: rgb(200, 200, 200);"  # Light text color
"}"
"QHeaderView::section{"
"background-color: rgb(40, 40, 40);"  # Dark header background color
"color: rgb(200, 200, 200);"  # Light header text color
"}")
        self.leaveTreeView.setObjectName("leaveTreeView")
        self.horizontalLayout_5.addWidget(self.leaveTreeView)
        self.verticalLayout_10.addLayout(self.horizontalLayout_5)
        self.leavePageUpdateButton = QtWidgets.QPushButton(self.leaveManagamentPage)
        self.leavePageUpdateButton.setStyleSheet("QPushButton{\n"
"border: 2px;\n"
"border-style:solid;\n"
"border-radius:6px;\n"
"background-color:rgb(0, 0, 0);\n"
"padding: 4px;\n"
"color:rgb(255, 255, 255);\n"
"border-color:rgb(81, 0, 255);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"border-bottom-color:rgb(0, 196, 113);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color:rgb(79, 79, 79)\n"
"}")
        self.leavePageUpdateButton.setObjectName("leavePageUpdateButton")
        self.verticalLayout_10.addWidget(self.leavePageUpdateButton, 0, QtCore.Qt.AlignHCenter)
        self.stackedWidget.addWidget(self.leaveManagamentPage)
        self.verticalLayout_2.addWidget(self.stackedWidget)
        self.verticalLayout.addWidget(self.widget)
        DashboardsWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(DashboardsWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        DashboardsWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(DashboardsWindow)
        self.statusbar.setObjectName("statusbar")
        DashboardsWindow.setStatusBar(self.statusbar)

        self.retranslateUi(DashboardsWindow)
        self.stackedWidget.setCurrentIndex(0)
        self.page1UserManagementButton.clicked.connect(lambda: self.stackedWidget.setCurrentIndex(1)) # type: ignore
        self.page1EmployeeInformationButton.clicked.connect(lambda: self.stackedWidget.setCurrentIndex(2)) # type: ignore
        self.page1LeaveManagementButton.clicked.connect(lambda: self.stackedWidget.setCurrentIndex(3)) # type: ignore
        self.employeeInformationButton.clicked.connect(lambda: self.stackedWidget.setCurrentIndex(2)) # type: ignore
        self.leaveManagementButton.clicked.connect(lambda: self.stackedWidget.setCurrentIndex(3)) # type: ignore
        self.userManagementButton.clicked.connect(lambda: self.stackedWidget.setCurrentIndex(1)) # type: ignore
        self.logoutButton.clicked.connect(DashboardsWindow.close) # type: ignore
        self.homeButton.clicked.connect(lambda: self.stackedWidget.setCurrentIndex(0)) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(DashboardsWindow)

        # other connections
        self.addEmployeeButton.clicked.connect(self.add_employee)
        self.updateEmployeeButton.clicked.connect(self.update_employee)
        self.employeeManagementTreeView.clicked.connect(self.on_treeview_item_clicked)
        self.leaveTreeView.clicked.connect(self.leave_tree_view_clicked)
        self.deleteEployeeButton.clicked.connect(self.delete_employee)
        self.searchField.textChanged.connect(lambda text: self.filter_tables(text))
        self.leavePageUpdateButton.clicked.connect(self.update_leave_info)


        self.proxy_model = QSortFilterProxyModel()
        self.proxy_model.setSourceModel(self.employeeInfoTreeView.model())
        self.employeeInfoTreeView.setModel(self.proxy_model)


    def filter_tables(self, search_text):
        # Get the search text from the search field
        search_text = search_text.lower()  # Convert to lowercase for case-insensitive search

        # Set the filter to match any part of the data
        self.proxy_model.setFilterKeyColumn(-1)  # -1 indicates all columns

        # Set the filter to match the search text using a wildcard
        self.proxy_model.setFilterWildcard(f'*{search_text}*')
        

    def on_treeview_item_clicked(self, index):
        # The slot function to handle item clicks in the tree view
        model = self.employeeInfoTreeView.model()
        row_data = [model.index(index.row(), col).data() for col in range(model.columnCount())]

        # Set data to corresponding fields
        self.empIdField.setText(row_data[0])
        self.empNameField.setText(row_data[1])
        self.genderComboBox.setCurrentText(row_data[2])
        self.statusComboBox.setCurrentText(row_data[3])
        self.positionComboBox.setCurrentText(row_data[4])
        self.salaryFIeld.setText(row_data[5])

    def leave_tree_view_clicked(self, index):
        # The slot function to handle item clicks in the tree view
        model = self.employeeInfoTreeView.model()
        row_data = [model.index(index.row(), col).data() for col in range(model.columnCount())]

        # Set data to corresponding fields
        self.leavePageStatusComboBox.setCurrentText(row_data[3])

        # Convert row_data[6] to integer before setting the value
        leave_days_str = row_data[6]
        leave_days = int(leave_days_str) if leave_days_str.isdigit() else 0  # Replace 0 with a default value if conversion fails
        self.leaveDaysSpinBox.setValue(leave_days)       

    def set_employee_data_in_tree_view(self):
        employees = database.fetch_employees()
        model = QStandardItemModel()
        model.setHorizontalHeaderLabels(["EmpId", "EmpName", "Gender", "Status", "Position", "Salary", "Days_on_leave"])
        
        for employee in employees:
                row_items = [QStandardItem(str(item)) for item in employee]
                model.appendRow(row_items)

        self.employeeManagementTreeView.setModel(model)
        self.employeeInfoTreeView.setModel(model)
        self.leaveTreeView.setModel(model)

        return model  # Return the created model

# ...

    def update_leave_info(self):
        # Get the selection model of the tree view
        selection_model = self.leaveTreeView.selectionModel()

        # Get the current index of the selection
        current_index = selection_model.currentIndex()

        if not current_index.isValid():
                # Handle the case where no item is selected
                return

        # Assuming the employee ID is in the first column (index 0)
        emp_id_index = current_index.siblingAtColumn(0)
        emp_id = emp_id_index.data()

        # Get the data directly from the model using the current index
        leave_days= self.leaveDaysSpinBox.value()
        leave_status = self.leavePageStatusComboBox.currentText()
  
        database.update_employee_leave(leave_days,leave_status,emp_id)
        self.set_employee_data_in_tree_view()
        leave_status = self.leavePageStatusComboBox.currentText()
        if leave_status == 'Active':
             leave_days = 0
             database.update_employee_leave(leave_days,leave_status,emp_id)
        self.set_employee_data_in_tree_view()
        self.clear_input_fields()



    def add_employee(self):
        # Retrieve data from the input fields and combo boxes
        emp_id = self.empIdField.text()
        emp_name = self.empNameField.text()
        gender = self.genderComboBox.currentText()
        status = self.statusComboBox.currentText()
        position = self.positionComboBox.currentText()
        salary = self.salaryFIeld.text()

        # check if employee arleady exists
        if database.get_employee(emp_id):
             self.clear_input_fields()
        else:
                # Send the data to the database
                database.insert_employee(emp_id, emp_name, gender, status, position, salary)

                # Optionally, update the tree view to reflect the changes
                self.set_employee_data_in_tree_view()

                # Optionally, clear the input fields after adding an employee
                self.clear_input_fields()

        

    def update_employee(self):
        # Retrieve data from the input fields and combo boxes
        emp_id = self.empIdField.text()

        # Check if an employee is selected
        if not emp_id:
            return

        emp_name = self.empNameField.text()
        gender = self.genderComboBox.currentText()
        status = self.statusComboBox.currentText()
        position = self.positionComboBox.currentText()
        salary = self.salaryFIeld.text()
        database.update_employee(emp_name, gender, status, position, salary, '', emp_id)
        self.set_employee_data_in_tree_view()
        self.clear_input_fields()

    def delete_employee(self):
         #deletes an employee from the database
        emp_id = self.empIdField.text()

        if not emp_id:
             return
        database.delete_employee(emp_id)
        self.set_employee_data_in_tree_view()
        self.clear_input_fields()

    def clear_input_fields(self):
        # Clear the input fields and combo boxes
        self.empIdField.clear()
        self.empNameField.clear()
        self.genderComboBox.setCurrentIndex(0)  # Set to the default index
        self.statusComboBox.setCurrentIndex(0)  # Set to the default index
        self.positionComboBox.setCurrentIndex(0)  # Set to the default index
        self.salaryFIeld.clear()


    def retranslateUi(self, DashboardsWindow):
        _translate = QtCore.QCoreApplication.translate
        DashboardsWindow.setWindowTitle(_translate("DashboardsWindow", "HR System"))
        self.homeButton.setText(_translate("DashboardsWindow", "Home"))
        self.userManagementButton.setText(_translate("DashboardsWindow", "Employee Management"))
        self.employeeInformationButton.setText(_translate("DashboardsWindow", "Employee Information"))
        self.leaveManagementButton.setText(_translate("DashboardsWindow", "Leave Management"))
        self.logoutButton.setText(_translate("DashboardsWindow", "Logout"))
        self.label_3.setText(_translate("DashboardsWindow", "HUMAN RESOURCE MANAGEMENT SYSTEM"))
        self.page1UserManagementButton.setText(_translate("DashboardsWindow", "EmployeeManagement"))
        self.page1EmployeeInformationButton.setText(_translate("DashboardsWindow", "Employee Information"))
        self.page1LeaveManagementButton.setText(_translate("DashboardsWindow", "Leave Management "))
        self.page1EmployeeRecruitmentButton.setText(_translate("DashboardsWindow", "Employee Recruitment"))
        self.label_2.setText(_translate("DashboardsWindow", "Employee Management"))
        self.label_6.setText(_translate("DashboardsWindow", "EmpId"))
        self.empIdField.setPlaceholderText(_translate("DashboardsWindow", "Enter Employee ID"))
        self.label_9.setText(_translate("DashboardsWindow", "EmpName"))
        self.empNameField.setPlaceholderText(_translate("DashboardsWindow", "Enter Employee Name"))
        self.label_11.setText(_translate("DashboardsWindow", "Gender"))
        self.label_10.setText(_translate("DashboardsWindow", "Status"))
        self.label_8.setText(_translate("DashboardsWindow", "Position"))
        self.label_7.setText(_translate("DashboardsWindow", "Salary"))
        self.salaryFIeld.setPlaceholderText(_translate("DashboardsWindow", "Enter Salary"))
        self.addEmployeeButton.setText(_translate("DashboardsWindow", "Add Employee"))
        self.updateEmployeeButton.setText(_translate("DashboardsWindow", "Update Employee"))
        self.deleteEployeeButton.setText(_translate("DashboardsWindow", "Delete Employee"))
        self.label_12.setText(_translate("DashboardsWindow", "Employee Information"))
        self.searchField.setPlaceholderText(_translate("DashboardsWindow", "Search"))
        self.label_13.setText(_translate("DashboardsWindow", "Leave Management"))
        self.label_15.setText(_translate("DashboardsWindow", "Status"))
        self.label_14.setText(_translate("DashboardsWindow", "Days"))
        self.leavePageUpdateButton.setText(_translate("DashboardsWindow", "Update Employee"))
import image_resources_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DashboardsWindow = QtWidgets.QMainWindow()
    ui = Ui_DashboardsWindow()
    ui.setupUi(DashboardsWindow)
    ui.set_employee_data_in_tree_view()
    DashboardsWindow.show()
    sys.exit(app.exec_())
